### ISSUE TITLE
-[AppDelegate window]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by AKACC** [nazrdogan/ReactNativeAppClips#2]
I tried your project and received this error. Could you take a look and give me some helps?
<img width="766" alt="Screen Shot 2020-08-25 at 6 36 04 PM" src="https://user-images.githubusercontent.com/22218449/91234813-16ff4380-e702-11ea-971c-ae2e4291ce0a.png">

**Comment by nazrdogan** [comment]
@AKACC  Could you please share repro steps ?

**Comment by AKACC** [comment]
@nazrdogan 
I followed steps. npm install then npx pod-install.

**Comment by AKACC** [comment]
@nazrdogan I found out the problem. Not sure what is the main reason. In my own project, I changed version matching the main project then it works.

**Comment by AKACC** [comment]
AfterI  successfully ran a few times, same error happenes.

**Comment by nazrdogan** [comment]
sorry for late answer. but which version Xcode you are using ? @AKACC
