### ISSUE TITLE
React-native unimodules

### ISSUE THREAD

**Issue by zRelux** [nazrdogan/ReactNativeAppClips#5]
Hey man I was wondering if you could give me a quick help on how to add react-native-unimodules to the app clip.
https://docs.expo.io/bare/installing-unimodules/

**Comment by zRelux** [comment]
I tried adding it to the view controller but I had no luck with that.

**Comment by nazrdogan** [comment]
As far I understand you should add AppDelegate of App Clip target. I have no time today, but I can check tomorrow.

**Comment by zRelux** [comment]
Can we hop on a discord call tomorrow? It would mean a lot

**Comment by zRelux** [comment]
Or maybe a tutorial online where I can see it how to do it

**Comment by nazrdogan** [comment]
I made a new sample without scenedelegate. basically, the structure is the same as the main. application.https://github.com/nazrdogan/AppClipsUniModules

**Comment by zRelux** [comment]
Sorry to bother you again but I seem to get a black screen and the app does not open

**Comment by nazrdogan** [comment]
any issue on console or xcode log ? did you run main app first because packager needs to run first.

**Comment by zRelux** [comment]
Hi sorry I didn't reply do you think we can hop on a discord call or something? I have been trying to add an app clip to an existing project so it has been difficult to figure out errors

**Comment by zRelux** [comment]
So i just cloned the repo and I
1. yarn
2. npx pod-install
3. yarn ios

And even on the regular app I get this warning `The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly`

which means that the modules are not connected correctly

**Comment by nazrdogan** [comment]
i didn't setup for main app, you should open Xcode and select App clip target (RNClip) then run.  i m not active on discord but my discord email nazrdogan@icloud.com

**Comment by zRelux** [comment]
Are you free now?

**Comment by zRelux** [comment]
I need your discord id as you cannot add by email on discord. If it is not your preferred thing we can make a google meet or anything else

**Comment by nazrdogan** [comment]
nazrdogan#1057 here is my discord

**Comment by zRelux** [comment]
Sent friend request
